"""rate to ratetime to datebase

Revision ID: 16b15aafac33
Revises: 2bcb27d32f17
Create Date: 2024-05-10 01:20:46.257347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b15aafac33'
down_revision: Union[str, None] = '2bcb27d32f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
