"""add_in_parking

Revision ID: 2bcb27d32f17
Revises: 4113f51b3bf2
Create Date: 2024-05-08 22:09:11.755659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bcb27d32f17'
down_revision: Union[str, None] = '4113f51b3bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'avto', ['number'])
    op.add_column('logs', sa.Column('in_parking', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'in_parking')
    op.drop_constraint(None, 'avto', type_='unique')
    # ### end Alembic commands ###
