"""Init

Revision ID: 352e7eb3be57
Revises: 26eef329883a
Create Date: 2024-05-13 22:40:52.137103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352e7eb3be57'
down_revision: Union[str, None] = '26eef329883a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('logs', 'billbalance')
    op.drop_column('logs', 'billcash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('billcash', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('billbalance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('logs', 'total')
    # ### end Alembic commands ###
